# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MySQL driver:
#   gem install mysql2
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: serpinspector_development
  pool: 5
  username: serpinspector
  password: ZcO5CihLeygQhmCm9UO0
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: serpinspector_test
  pool: 5
  username: serpinspector
  password: ZcO5CihLeygQhmCm9UO0
  host: localhost

production:
 adapter: mysql2
 encoding: utf8
 reconnect: false
 database: serpinspector_production
 pool: 5
 username: serpinspector
 password: ZcO5CihLeygQhmCm9UO0
 host: localhost
